version: '3.8'

services:
  jenkins:
    image: jenkins-docker-custom
    container_name: jenkins-docker
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: jenkins
    restart: unless-stopped

volumes:
  jenkins-data:
